services:
  - type: web
    name: JobAgent-Backend
    env: python
    region: oregon
    plan: free
    root: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

  - type: static
    name: JobAgent-Frontend
    env: static
    region: oregon
    plan: free
    root: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
